### ISSUE TITLE
[AtributeError]: module 'click.utils' has no attribute '_expand_args'

### ISSUE THREAD

**Issue by Woisek** [Sanster/tldream#4]
Can't start tldream because it throws the following error:

I:\Super SD 2.0\tldream>start.bat

I:\Super SD 2.0\tldream>tldream --model "I:\stable_diffusion_shared\models\Stable-diffusion\SD v1.5\v1-5-pruned-emaonly_(3.97GB).ckpt" --listen "localhost" --no-nsfw-filter --local-files-only
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ F:\Programme\Python310\lib\runpy.py:196 in _run_module_as_main                                   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ F:\Programme\Python310\lib\runpy.py:86 in _run_code                                              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from tldream import entry_point                                                              │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(entry_point())                                                                  │
│   8                                                                                              │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\tldream\__init__.py:63 in entry_point                   │
│                                                                                                  │
│   60                                                                                             │
│   61                                                                                             │
│   62 def entry_point():                                                                          │
│ ❱ 63 │   typer_app()                                                                             │
│   64                                                                                             │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\typer\main.py:328 in __call__                           │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\typer\main.py:311 in __call__                           │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\click\core.py:829 in __call__                           │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\typer\core.py:716 in main                               │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\typer\core.py:190 in _main                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'click.utils' has no attribute '_expand_args'

Any ideas?

**Comment by Sanster** [comment]
try `pip install --upgrade click`

**Comment by Woisek** [comment]
OK, now I got this:

I:\Super SD 2.0\tldream>start.bat

I:\Super SD 2.0\tldream>tldream --model "I:\stable_diffusion_shared\models\Stable-diffusion\SD v1.5\v1-5-pruned-emaonly_(3.97GB).ckpt" --listen "localhost" --no-nsfw-filter --local-files-only
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Usage: tldream [OPTIONS]
Try 'tldream --help' for help.
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Got unexpected extra argument (localhost)                                                                                                                   │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

I:\Super SD 2.0\tldream>

**Comment by Sanster** [comment]
Remove  --listen "localhost"

**Comment by Woisek** [comment]
So, how do I set the IP to open the server? The suggested http://0.0.0.0:4242 does not work (Error: Connection failed) and using my local IP http://192.168.1.9:4242/ throws an error:

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4242 (Press CTRL+C to quit)
INFO:     ('192.168.1.9', 56327) - "WebSocket /socket.io/?EIO=4&transport=websocket" [accepted]
INFO:     connection open
INFO:     ('192.168.1.9', 56475) - "WebSocket /socket.io/?EIO=4&transport=websocket" [accepted]
INFO:     connection open
INFO:     192.168.1.9:56479 - "GET /tldraw-assets.json HTTP/1.1" 404 Not Found
2023-06-01 11:06:26.168 | INFO     | tldream.server:run:75 - {'steps': 15, 'guidance_scale': 9.0, 'prompt': 'an ared apple', 'negative_prompt': 'lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality', 'width': 512, 'height': 512}
2023-06-01 11:06:26.973 | INFO     | tldream.util:ckpt_process:286 - Original image shape: (230, 185, 3)
2023-06-01 11:06:26.976 | INFO     | tldream.util:ckpt_process:292 - Resized image shape: (512, 512, 3)
2023-06-01 11:06:26.990 | INFO     | tldream.server:run:114 - process time: 814.7923946380615ms
INFO:     192.168.1.9:56479 - "POST /run HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\Programme\Python310\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\Programme\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "F:\Programme\Python310\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "F:\Programme\Python310\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\Programme\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\Programme\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\Programme\Python310\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "F:\Programme\Python310\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "F:\Programme\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\Programme\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\Programme\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\Programme\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\Programme\Python310\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "F:\Programme\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\Programme\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "F:\Programme\Python310\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "F:\Programme\Python310\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "F:\Programme\Python310\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "F:\Programme\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Programme\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\Programme\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\Programme\Python310\lib\site-packages\tldream\server.py", line 90, in run
    res_rgb_img = process(
  File "F:\Programme\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\Programme\Python310\lib\site-packages\tldream\util.py", line 375, in process
    return ckpt_process(
  File "F:\Programme\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\Programme\Python310\lib\site-packages\tldream\util.py", line 300, in ckpt_process
    control = einops.rearrange(control, "b h w c -> b c h w").clone()
  File "F:\Programme\Python310\lib\site-packages\einops\einops.py", line 424, in rearrange
    return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)
  File "F:\Programme\Python310\lib\site-packages\einops\einops.py", line 368, in reduce
    return recipe.apply(tensor)
  File "F:\Programme\Python310\lib\site-packages\einops\einops.py", line 203, in apply
    backend = get_backend(tensor)
  File "F:\Programme\Python310\lib\site-packages\einops\_backends.py", line 49, in get_backend
    if backend.is_appropriate_type(tensor):
  File "F:\Programme\Python310\lib\site-packages\einops\_backends.py", line 513, in is_appropriate_type
    return self.K.is_tensor(tensor) and self.K.is_keras_tensor(tensor)
AttributeError: module 'keras.backend' has no attribute 'is_tensor'

**Comment by Sanster** [comment]
- when start without `--listen`, you can visit  http://127.0.0.1:4242 in you browser
- If you want to visit from other PC, you can add just `--listen`, your IP address needs to be found by yourself, maybe this can help. https://support.microsoft.com/en-us/windows/find-your-ip-address-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9
- The error you are experiencing here is likely related to TensorFlow. Try running "pip uninstall tensorflow tensorflow-gpu" before start server to see if it resolves the issue.

**Comment by Woisek** [comment]
>Try running "pip uninstall tensorflow tensorflow-gp

But it seems that want to uninstall tensoflow from my main python ... ?! I need tensorflow for other repos, respectively other repos need it.
